### ISSUE TITLE
New Blog Post on WebRTCinWebkit website

### ISSUE THREAD

**Issue by manuelroth** [WebRTCinWebKit/webkit-webrtc-tests#2]
Hi @adam-be,
Really like the mission of this project. I have been wondering if you could share some news about status of the implementation. The last blog post on [webrtcinwebkit.org](http://www.webrtcinwebkit.org/blog/) is from the end of 2015, there has probably been a lot of progress since then. Really like that you are taking the effort of bringing WebRTC finally to Webkit.

Kind regards,
Manuel

**Comment by adam-be** [comment]
Hi @manuelroth 
Thanks for dropping by. There has indeed been a lot of progress since the 2015 blog post. We have upstreamed a lot of code from our fork to the WebKit main repository. [1] is a "meta bug" that keeps track of our issues and patces. I'll perhaps post a new blog post in a few weeks.

[1] https://bugs.webkit.org/show_bug.cgi?id=143211

**Comment by manuelroth** [comment]
Thanks for your response. Really looking forward to a new blog post in the coming weeks. I find it always hard to understand what is going on from looking at issues and patches alone.

**Comment by agouaillard** [comment]
You can see more on the webkit trac system itself. Note that when adam says "upstream", he means both for webkit (generic, shared with safari), and webkitGTK (the linux browser based on webkit). I.E. it doe snot mean that all the upstream code finds its way in safari. Most of the GetUserMedia Code did, but there is a question mark next to the peerConnection code. As far as Safari is concerned, we should know more in a month (adam, eric is going to TPAC in lisbon, will yo ube there, or only stefan is making the trip?)

**Comment by adam-be** [comment]
@agouaillard, I will be in Lisbon

**Comment by manuelroth** [comment]
Just saw that you published a [new blog post](http://www.webrtcinwebkit.org/blog/2016/11/9/openwebrtc-in-webkit-upstream-complete), great to see all of this progress around WebRTC in webkit. Will close this issue.
